# Imagen base: Node.js versión LTS, variante "slim" (más liviana)
FROM node:20-slim

#Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos primero solo package.json y package-lock.json
# (truco de cacheo: si no cambian, Docker no reinstala dependencias en cada build)

COPY package*.json ./

RUN npm install

# Ahora sí copiamos el resto del código
COPY . .

# Puerto en el que escucha tu app Express/Node
EXPOSE 3001

# Comando para arrancar la app
CMD ["npm", "start"]